SELECT UPPER(SNAME), AGE FROM Sailor_219;

SELECT * FROM Sailor_219 ORDER BY SNAME;

SELECT DISTINCT(SNAME) FROM Sailor_219;

SELECT DISTINCT SNAME, RATING FROM Sailor_219 WHERE RATING BETWEEN 5 AND 10;

SELECT * FROM Sailor_219 ORDER BY RATING, AGE DESC;

SELECT * FROM Sailor_219 WHERE SNAME = 'Horatio' AND AGE = 35.5;

SELECT S.SNAME FROM Sailor_219 S, Reserved_219 R WHERE S.SID = R.SID AND R.BID = 104;

SELECT S.SNAME FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND R.BID = B.BID AND COLOR = 'red';

SELECT SNAME FROM Sailor_219 WHERE RATING IS NOT NULL;

SELECT SNAME FROM Sailor_219 WHERE RATING IS NULL;

SELECT COLOR FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND R.BID = B.BID AND SNAME = 'Lubber';

SELECT SNAME FROM Sailor_219 S, Reserved_219 R WHERE S.SID = R.SID GROUP BY(SNAME);

SELECT SNAME FROM Sailor_219 WHERE SNAME LIKE 'B__%' AND SNAME LIKE '%b';

SELECT SNAME FROM Sailor_219 WHERE SNAME LIKE 'B_b';

SELECT DISTINCT S.SNAME, B.COLOR FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND R.BID = B.BID AND (COLOR = 'red' OR COLOR = 'green');

SELECT S.SID, S.SNAME, B.COLOR FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND R.BID = B.BID AND COLOR = 'red'
MINUS
SELECT S.SID, S.SNAME, B.COLOR FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND R.BID = B.BID AND COLOR = 'green';

SELECT S.SNAME, R.BID FROM Sailor_219 S, Reserved_219 R WHERE S.SID = R.SID AND BID = 103;

SELECT S.SNAME FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND B.COLOR = 'red';

SELECT SID, SNAME FROM Sailor_219
MINUS
SELECT S.SID, SNAME FROM Sailor_219 S, Boat_219 B, Reserved_219 R WHERE S.SID = R.SID AND R.BID = B.BID AND B.COLOR = 'red';

SELECT * FROM Sailor_219 WHERE RATING > (SELECT MIN(RATING) FROM Sailor_219 WHERE SNAME = 'Horatio');

SELECT AVG(AGE) FROM Sailor_219 WHERE RATING = 10;

SELECT SNAME FROM Sailor_219 WHERE AGE > (SELECT MAX(AGE) FROM Sailor_219 WHERE RATING = 10);

SELECT MIN(AGE) FROM Sailor_219 WHERE RATING IS NOT NULL GROUP BY(RATING) ORDER BY RATING;

SELECT SNAME FROM Sailor_219 WHERE AGE > 17 AND RATING IS NOT NULL ORDER BY(RATING);

SELECT AVG(AGE) FROM Sailor_219 GROUP BY(RATING) HAVING COUNT(SID) >= 2;

SELECT COUNT(R.SID) FROM Boat_219 B,Reserved_219 R WHERE B.BID = R.BID AND B.COLOR = 'red';

SELECT * FROM Sailor_219 WHERE RATING = (SELECT MAX(RATING) FROM Sailor_219 WHERE RATING < (SELECT MAX(RATING) FROM Sailor_219)); 

SELECT SNAME FROM Sailor_219 WHERE RATING = (SELECT MIN(RATING) FROM Sailor_219 WHERE RATING > (SELECT MIN(RATING) FROM Sailor_219 WHERE RATING > (SELECT MIN(RATING) FROM Sailor_219)));

SELECT SID FROM Reserved_219 R GROUP BY (R.SID) HAVING COUNT(DISTINCT R.BID) = (SELECT COUNT(BID) FROM Boat_219);

SELECT * FROM Sailor_219 WHERE SID IN (SELECT SID FROM Reserved_219 GROUP BY SID HAVING COUNT(BID) > 2);
