SELECT PNUMBER, DNUM, LNAME, ADDRESS, BDATE FROM PROJECT_219,DEPARTMENT_219, EMPLOYEE_219 WHERE DNUM = DNUMBER AND MGRSSN = SSN AND PLOCATION = 'Stafford';

SELECT * FROM EMPLOYEE_219 WHERE NOT EXISTS((SELECT PNUMBER FROM PROJECT_219 WHERE DNUM=5) MINUS (SELECT PNO FROM WORKS_ON_219 WHERE SSN = ESSN));

SELECT PNUMBER FROM PROJECT_219, DEPARTMENT_219,EMPLOYEE_219 WHERE DNUM=DNUMBER AND MGRSSN=SSN AND LNAME = 'Smith' 
UNION 
SELECT PNUMBER FROM PROJECT_219,  WORKS_ON_219, EMPLOYEE_219 WHERE PNUMBER=PNO AND ESSN=SSN AND LNAME = 'Smith';

SELECT FNAME,LNAME FROM EMPLOYEE_219 WHERE SSN NOT IN(SELECT ESSN FROM DEPENDENT_219);

SELECT FNAME,LNAME FROM EMPLOYEE_219, DEPARTMENT_219, DEPENDENT_219 WHERE SSN = MGRSSN AND SSN=ESSN;

SELECT E.FNAME AS "EMPLOYEE FNAME", E.LNAME AS "EMPLOYEE LNAME", S.FNAME AS "SUPERVISER FNAME", S.LNAME AS "SUPERVISER LNAME" FROM EMPLOYEE_219 E, EMPLOYEE_219 S WHERE E.SUPERSSN = S.SSN;

SELECT FNAME, (SALARY*1.1), PNAME FROM EMPLOYEE_219, PROJECT_219, WORKS_ON_219 WHERE SSN=ESSN AND PNO=PNUMBER AND PNAME='ProductX';

SELECT FNAME, LNAME, PNAME, DNAME FROM EMPLOYEE_219, PROJECT_219, WORKS_ON_219, DEPARTMENT_219 WHERE SSN=ESSN AND PNO=PNUMBER AND DNO=DNUMBER ORDER BY DNAME, LNAME, FNAME;

SELECT FNAME FROM EMPLOYEE_219 WHERE SUPERSSN IS NULL;

SELECT FNAME FROM EMPLOYEE_219, DEPENDENT_219 WHERE FNAME = DEPENDENT_NAME;

SELECT DISTINCT(ESSN), PNO FROM WORKS_ON_219 WHERE PNO<3;

SELECT FNAME, LNAME FROM EMPLOYEE_219 WHERE SALARY > ALL(SELECT SALARY FROM EMPLOYEE_219 WHERE DNO=5);

SELECT SUM(SALARY), MAX(SALARY), MIN(SALARY), AVG(SALARY) FROM EMPLOYEE_219;

SELECT SUM(SALARY), MAX(SALARY), MIN(SALARY), AVG(SALARY) FROM EMPLOYEE_219, DEPARTMENT_219 WHERE DNO=DNUMBER AND DNAME='Research';

SELECT FNAME, SSN FROM EMPLOYEE_219 WHERE SSN IN (SELECT ESSN FROM DEPENDENT_219 GROUP BY ESSN HAVING COUNT(*)>1);

SELECT COUNT(*) FROM EMPLOYEE_219 WHERE SALARY > 20000 GROUP BY DNO HAVING COUNT(SSN) > 2;

SELECT PNUMBER, PNAME, COUNT(*) FROM PROJECT_219, WORKS_ON_219 WHERE PNO=PNUMBER GROUP BY PNUMBER, PNAME;

SELECT PNUMBER, PNAME, COUNT(ESSN) FROM PROJECT_219, WORKS_ON_219 WHERE PNO=PNUMBER GROUP BY PNUMBER, PNAME HAVING COUNT(ESSN)>2;

SELECT PNUMBER,PNAME,COUNT(*) FROM PROJECT_219, WORKS_ON_219 WHERE PNUMBER=PNO AND DNUM=5 GROUP BY PNUMBER,PNAME;

SELECT DNO, COUNT(*) FROM EMPLOYEE_219 WHERE SALARY>20000 GROUP BY DNO HAVING COUNT(*)>2;